name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  WORKFLOW_URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Black
        uses: psf/black@stable

  diff:
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: cdk diff
        run: |
          cdk diff --no-color 2>&1 | tee cdk.log
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BOT_TIMEZONE: ${{ secrets.BOT_TIMEZONE }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}

      - name: Add comment to PR
        run: |
          sed -in '1,/^Stack rialto-bus-bot.*/d' cdk.log
          jq --raw-input --slurp '{body: ("```" + . + "```")}' cdk.log > cdk.log.json
          curl \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d @cdk.log.json \
            -X POST \
            $URL
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: cdk deploy
        run: |
          cdk deploy --require-approval never --force true --progress events
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BOT_TIMEZONE: ${{ secrets.BOT_TIMEZONE }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
