name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Black
        uses: jpetrucciani/black-check@6ccaad6b470e4f5999d70021474781a53769ed71

  diff:
    needs: lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: cdk diff
        run: |
          cdk diff
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BOT_TIMEZONE: ${{ secrets.BOT_TIMEZONE }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}

  deploy:
    needs: diff
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: cdk deploy
        run: |
          cdk deploy --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BOT_TIMEZONE: ${{ secrets.BOT_TIMEZONE }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
